const { Order, MenuItem, Notification, Offer } = require('../models');
const { generatePaymentQR } = require('../utils/upiQR');

// @desc    Create new order
// @route   POST /api/orders
// @access  Public
exports.createOrder = async (req, res) => {
  try {
    const { customer, items, discountCode, paymentMethod, paymentStatus, notes } = req.body;

    // Validate items and calculate totals
    let subtotal = 0;
    const orderItems = [];

    for (const item of items) {
      const menuItem = await MenuItem.findById(item.menuItem);
      if (!menuItem) {
        return res.status(400).json({
          success: false,
          message: `Menu item ${item.menuItem} not found`
        });
      }
      if (!menuItem.isAvailable) {
        return res.status(400).json({
          success: false,
          message: `${menuItem.name} is currently unavailable`
        });
      }

      const itemSubtotal = menuItem.price * item.quantity;
      subtotal += itemSubtotal;

      orderItems.push({
        menuItem: menuItem._id,
        name: menuItem.name,
        price: menuItem.price,
        quantity: item.quantity,
        subtotal: itemSubtotal
      });
    }

    // Apply discount if code provided
    let discount = 0;
    if (discountCode) {
      const offer = await Offer.findOne({ code: discountCode.toUpperCase() });
      if (offer && offer.isValid()) {
        discount = offer.calculateDiscount(subtotal);
        offer.usedCount += 1;
        await offer.save();
      }
    }

    const total = subtotal - discount;

    // Create order (tokenNumber is auto-generated by pre-save hook)
    const order = await Order.create({
      customer,
      items: orderItems,
      subtotal,
      discount,
      discountCode: discountCode ? discountCode.toUpperCase() : undefined,
      total,
      paymentMethod,
      paymentStatus: paymentStatus || 'pending',
      notes,
      statusHistory: [{ status: 'new', timestamp: new Date() }]
    });

    // Create notification with token number
    const notification = await Notification.create({
      type: 'new_order',
      title: 'New Order Received',
      message: `Token #${order.tokenNumber} — ${customer.name} — ₹${total}`,
      order: order._id
    });

    // Emit socket events
    if (req.io) {
      req.io.emit('newOrder', order);
      req.io.emit('notification', notification);
    }

    // Generate dynamic payment QR for online/upi payments
    let paymentQR = null;
    if (paymentMethod && ['upi', 'online'].includes(paymentMethod)) {
      try {
        paymentQR = await generatePaymentQR({
          amount: total,
          orderId: order.orderNumber,
          tokenNumber: order.tokenNumber,
        });
      } catch (qrError) {
        console.warn('QR generation skipped:', qrError.message);
      }
    }

    res.status(201).json({
      success: true,
      data: order,
      paymentQR
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: error.message
    });
  }
};

// @desc    Get all orders
// @route   GET /api/orders
// @access  Private
exports.getOrders = async (req, res) => {
  try {
    const { status, date, limit = 50, page = 1 } = req.query;
    
    let query = {};
    
    if (status) query.status = status;
    if (date) {
      const startDate = new Date(date);
      startDate.setHours(0, 0, 0, 0);
      const endDate = new Date(date);
      endDate.setHours(23, 59, 59, 999);
      query.createdAt = { $gte: startDate, $lte: endDate };
    }

    const orders = await Order.find(query)
      .sort({ createdAt: -1 })
      .limit(parseInt(limit))
      .skip((parseInt(page) - 1) * parseInt(limit))
      .populate('items.menuItem', 'name image');

    const total = await Order.countDocuments(query);

    res.json({
      success: true,
      count: orders.length,
      total,
      pages: Math.ceil(total / parseInt(limit)),
      data: orders
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: error.message
    });
  }
};

// @desc    Get orders by status (for Kanban)
// @route   GET /api/orders/kanban
// @access  Private
exports.getOrdersByStatus = async (req, res) => {
  try {
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    const statuses = ['new', 'preparing', 'ready', 'completed'];
    const kanbanData = {};

    for (const status of statuses) {
      kanbanData[status] = await Order.find({
        status,
        createdAt: { $gte: today }
      })
        .sort({ tokenNumber: status === 'completed' ? -1 : 1 })
        .limit(status === 'completed' ? 20 : 100);
    }

    res.json({
      success: true,
      data: kanbanData
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: error.message
    });
  }
};

// @desc    Get live order queue for admin (today's active orders by token)
// @route   GET /api/orders/queue
// @access  Private
exports.getOrderQueue = async (req, res) => {
  try {
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    // Active orders: not completed and not cancelled
    const activeOrders = await Order.find({
      createdAt: { $gte: today },
      status: { $in: ['new', 'preparing', 'ready'] }
    })
      .sort({ tokenNumber: 1 })
      .select('tokenNumber orderNumber customer.name items status paymentMethod paymentStatus total createdAt');

    // Completed today
    const completedOrders = await Order.find({
      createdAt: { $gte: today },
      status: 'completed'
    })
      .sort({ tokenNumber: -1 })
      .limit(20)
      .select('tokenNumber orderNumber customer.name status paymentMethod paymentStatus total createdAt');

    // Today's summary
    const todayOrders = await Order.find({ createdAt: { $gte: today } });
    const summary = {
      totalTokensToday: todayOrders.length,
      activeOrders: activeOrders.length,
      completedOrders: todayOrders.filter(o => o.status === 'completed').length,
      pendingPayments: todayOrders.filter(o => o.paymentStatus === 'pending' && o.status !== 'cancelled').length,
      todayRevenue: todayOrders
        .filter(o => o.status !== 'cancelled')
        .reduce((sum, o) => sum + o.total, 0)
    };

    res.json({
      success: true,
      data: {
        active: activeOrders,
        completed: completedOrders,
        summary
      }
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: error.message
    });
  }
};

// @desc    Get single order
// @route   GET /api/orders/:id
// @access  Private
exports.getOrder = async (req, res) => {
  try {
    const order = await Order.findById(req.params.id)
      .populate('items.menuItem', 'name image category');

    if (!order) {
      return res.status(404).json({
        success: false,
        message: 'Order not found'
      });
    }

    res.json({
      success: true,
      data: order
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: error.message
    });
  }
};

// @desc    Update order status
// @route   PATCH /api/orders/:id/status
// @access  Private
exports.updateOrderStatus = async (req, res) => {
  try {
    const { status } = req.body;
    const validStatuses = ['new', 'preparing', 'ready', 'completed', 'cancelled'];

    if (!validStatuses.includes(status)) {
      return res.status(400).json({
        success: false,
        message: 'Invalid status'
      });
    }

    const order = await Order.findById(req.params.id);

    if (!order) {
      return res.status(404).json({
        success: false,
        message: 'Order not found'
      });
    }

    order.status = status;
    order.statusHistory.push({
      status,
      timestamp: new Date(),
      updatedBy: req.user ? req.user._id : null
    });

    await order.save();

    // Emit socket event
    if (req.io) {
      req.io.emit('orderUpdated', order);
    }

    res.json({
      success: true,
      data: order
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: error.message
    });
  }
};

// @desc    Get order by order number (for tracking)
// @route   GET /api/orders/track/:orderNumber
// @access  Public
exports.trackOrder = async (req, res) => {
  try {
    const order = await Order.findOne({ orderNumber: req.params.orderNumber })
      .select('orderNumber tokenNumber status statusHistory items total paymentMethod paymentStatus customer.name createdAt');

    if (!order) {
      return res.status(404).json({
        success: false,
        message: 'Order not found'
      });
    }

    res.json({
      success: true,
      data: order
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: error.message
    });
  }
};

// @desc    Update payment status
// @route   PATCH /api/orders/:id/payment
// @access  Private
exports.updatePaymentStatus = async (req, res) => {
  try {
    const { paymentStatus } = req.body;
    const validStatuses = ['pending', 'paid', 'cash_received', 'online_verified'];

    if (!validStatuses.includes(paymentStatus)) {
      return res.status(400).json({
        success: false,
        message: 'Invalid payment status. Use: pending, paid, cash_received, or online_verified'
      });
    }

    const order = await Order.findById(req.params.id);

    if (!order) {
      return res.status(404).json({
        success: false,
        message: 'Order not found'
      });
    }

    order.paymentStatus = paymentStatus;
    await order.save();

    // Emit socket event
    if (req.io) {
      req.io.emit('orderUpdated', order);
      req.io.emit('paymentUpdated', {
        orderId: order._id,
        tokenNumber: order.tokenNumber,
        paymentStatus,
        paymentMethod: order.paymentMethod
      });
    }

    res.json({
      success: true,
      data: order
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: error.message
    });
  }
};

// @desc    Get or regenerate payment QR for an order
// @route   GET /api/orders/:id/payment-qr
// @access  Public (customer needs this to pay)
exports.getPaymentQR = async (req, res) => {
  try {
    const order = await Order.findById(req.params.id)
      .select('orderNumber tokenNumber total paymentMethod paymentStatus customer.name');

    if (!order) {
      return res.status(404).json({
        success: false,
        message: 'Order not found'
      });
    }

    // Don't generate QR if already paid
    if (['paid', 'cash_received', 'online_verified'].includes(order.paymentStatus)) {
      return res.json({
        success: true,
        data: order,
        paymentQR: null,
        message: 'Payment already completed'
      });
    }

    const paymentQR = await generatePaymentQR({
      amount: order.total,
      orderId: order.orderNumber,
      tokenNumber: order.tokenNumber,
    });

    res.json({
      success: true,
      data: order,
      paymentQR
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: error.message
    });
  }
};

// @desc    Delete order
// @route   DELETE /api/orders/:id
// @access  Private/Admin
exports.deleteOrder = async (req, res) => {
  try {
    const order = await Order.findById(req.params.id);

    if (!order) {
      return res.status(404).json({
        success: false,
        message: 'Order not found'
      });
    }

    await order.deleteOne();

    // Emit socket event
    if (req.io) {
      req.io.emit('orderDeleted', req.params.id);
    }

    res.json({
      success: true,
      message: 'Order deleted'
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: error.message
    });
  }
};
